title: Aon Sceal
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://aonsceal.github.io/index.html
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact



google_analytics: "UA-58263416-1"
